#!/usr/bin/env node
// scrub — remove Claude attribution from a GitHub issue, PR, comment or review body (O09, K006).
//
//   node .harness/tools/scrub.mjs            in Actions (harness-scrub.yml): reads the event, re-reads
//                                            the body it names, and saves it back only if scrubbing changed it
//   node .harness/tools/scrub.mjs --stdin    prints the scrubbed text of stdin (tests, local use)
//
// What goes: a footer line "Generated by/with Claude Code", a Co-authored-by line for
// noreply@anthropic.com, a Claude-Session line, and every claude.ai link (a Markdown link loses its
// text too, a link ending a line the separator before it); a line left with no words, and a `---`
// rule left dangling at the end, go with them. Code blocks, inline code and HTML attribute values are
// left alone, so a body can still quote these strings on purpose. Everything else is unchanged.
//
// Safe on untrusted input: the body is only data to a few linear regexes, no code is checked out
// from the event, and the edit is made with GITHUB_TOKEN, whose events start no workflow (no loop).

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

// Line-level: only a footer- or trailer-shaped line goes, never a sentence that merely mentions it.
const GENERATED = /^[ \t]*(?:[^\w\s]{1,4}[ \t]{0,4})?[_*]{0,2}[ \t]{0,4}generated[ \t]{1,4}(?:by|with)[ \t]{1,4}\[?claude[ \t_-]{0,2}code\b/i;
const TRAILER = /^[ \t]*(?:co-authored-by:[^\n]{0,200}noreply@anthropic\.com|claude-session:[ \t]{0,4}https?:\/\/)/i;
// claude.ai and its subdomains only; bounded quantifiers keep every scan linear (no ReDoS)
const HOST = String.raw`https?:\/\/(?:[a-z0-9-]{1,63}\.){0,4}claude\.ai(?![\w-]|\.\w)(?:[/?#][^\s)>\]"'<]{0,2000})?`;
// a link at the end of a line takes the separator before it: "by X · [thread](…)_" → "by X_"
const TAIL = new RegExp(String.raw`[ \t]{0,20}(?:[·•,:–—-][ \t]{0,20})?(?:\[[^\]\n]{0,500}\]\([ \t]{0,4}<?${HOST}>?[ \t]{0,4}\)|<?${HOST}>?)(?=[_*]{0,3}[ \t]{0,20}$)`, 'gi');
// elsewhere a link goes with one space before it, and with parentheses that held only it
const MID = new RegExp(String.raw`(?:[ \t]?\[[^\]\n]{0,500}\]\([ \t]{0,4}<?${HOST}>?[ \t]{0,4}\)|[ \t]?\([ \t]{0,4}<?${HOST}>?[ \t]{0,4}\)|[ \t]?<?${HOST}>?)`, 'gi');

/** Remove claude.ai links from one line, leaving inline code spans and HTML attribute values alone. */
function unlink(line) {
  return line.split(/(`+[^`]*`+)/).map((part, i) => {
    if (i % 2) return part; // an inline code span
    // an attribute value (href="…", src='…') is markup, not a link to strip
    return part.replace(TAIL, (m, off, all) => (/=[ \t]*["']?$/.test(all.slice(0, off)) ? m : ''))
      .replace(MID, (m, off, all) => (/=[ \t]*["']?$/.test(all.slice(0, off + (m[0] === ' ' || m[0] === '\t' ? 1 : 0))) ? m : ''));
  }).join('');
}

/** The text without Claude attribution. Returns the input unchanged when there is none. */
export function scrub(text) {
  if (typeof text !== 'string' || !text) return text;
  const eol = text.includes('\r\n') ? '\r\n' : '\n';
  const out = [];
  let fence = null, removed = false;
  for (const line of text.split(/\r?\n/)) {
    const f = line.match(/^[ \t]{0,3}(`{3,}|~{3,})/);
    if (fence) { out.push(line); if (f && f[1][0] === fence[0] && f[1].length >= fence.length) fence = null; continue; }
    if (f) { fence = f[1]; out.push(line); continue; }
    if (GENERATED.test(line) || TRAILER.test(line)) { removed = true; continue; }
    const l = /claude\.ai/i.test(line) ? unlink(line) : line;
    if (l !== line) {
      removed = true;
      if (!/[\p{L}\p{N}]/u.test(l)) continue; // nothing but the link was on the line
    }
    out.push(l);
  }
  if (!removed) return text;
  while (out.length && out.at(-1).trim() === '') out.pop();
  if (out.length && /^[ \t]*(-{3,}|\*{3,}|_{3,})[ \t]*$/.test(out.at(-1))) { out.pop(); while (out.length && out.at(-1).trim() === '') out.pop(); }
  return out.join(eol).replace(/(\r?\n){3,}/g, `${eol}${eol}`) + (/\r?\n$/.test(text) && out.length ? eol : '');
}

// --- GitHub Actions entry point -------------------------------------------------------------------------
/** The REST path of the body an event names, and how to save it. */
export function target(name, p) {
  const repo = p.repository?.full_name;
  if (!repo) return null;
  if (name === 'issues' && p.issue) return { path: `/repos/${repo}/issues/${p.issue.number}`, method: 'PATCH' };
  if ((name === 'pull_request_target' || name === 'pull_request') && p.pull_request) return { path: `/repos/${repo}/pulls/${p.pull_request.number}`, method: 'PATCH' };
  if (name === 'issue_comment' && p.comment) return { path: `/repos/${repo}/issues/comments/${p.comment.id}`, method: 'PATCH' };
  if (name === 'pull_request_review_comment' && p.comment) return { path: `/repos/${repo}/pulls/comments/${p.comment.id}`, method: 'PATCH' };
  if (name === 'pull_request_review' && p.review && p.pull_request) return { path: `/repos/${repo}/pulls/${p.pull_request.number}/reviews/${p.review.id}`, method: 'PUT' };
  return null;
}

async function api(method, path, body) {
  const r = await fetch(`${process.env.GITHUB_API_URL || 'https://api.github.com'}${path}`, {
    method,
    headers: {
      accept: 'application/vnd.github+json', 'x-github-api-version': '2022-11-28', 'user-agent': 'harness-kit-scrub',
      authorization: `Bearer ${process.env.GITHUB_TOKEN}`, ...(body ? { 'content-type': 'application/json' } : {}),
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  const text = await r.text();
  if (!r.ok) { const e = new Error(`${method} ${path} answered ${r.status}: ${text.slice(0, 200)}`); e.status = r.status; throw e; }
  return JSON.parse(text);
}

async function main() {
  if (process.argv.includes('--stdin')) { process.stdout.write(scrub(readFileSync(0, 'utf8'))); return; }
  const name = process.env.GITHUB_EVENT_NAME;
  const t = target(name, JSON.parse(readFileSync(process.env.GITHUB_EVENT_PATH, 'utf8')));
  if (!t) { console.log(`scrub: nothing to scrub on ${name}`); return; }
  if (!process.env.GITHUB_TOKEN) throw new Error('GITHUB_TOKEN is not set');
  // re-read: the event's copy may be older than a later edit, which must not be overwritten
  const now = await api('GET', t.path);
  const clean = scrub(now.body);
  if (clean === now.body) { console.log(`scrub: ${t.path}: no attribution`); return; }
  try {
    await api(t.method, t.path, { body: clean });
  } catch (e) {
    // a fork PR's review events get a read-only token: say so on the run, do not turn it red
    if (e.status === 403 && process.env.GITHUB_EVENT_NAME?.startsWith('pull_request_review')) { console.log(`::warning::scrub: ${t.path}: attribution left; this event's token is read-only (${e.message})`); return; }
    throw e;
  }
  console.log(`scrub: ${t.path}: attribution removed`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main().catch((e) => { console.error(`scrub: ${e.message}`); process.exit(1); });
}
